#ifndef __KZ_TD_SYS_H
#define __KZ_TD_SYS_H

#include "common.h"
#include "kazuya/bios.h"

typedef struct { // 0x8
    /* 0x0 */ DVECTOR str_offset;
    /* 0x4 */ s32 str_no;
} PARA_DC_STD;

typedef struct { // 0x10
    /* 0x0 */ DVECTOR str_offset;
    /* 0x4 */ s32 str_no;
    /* 0x8 */ DVECTOR gim_offset;
    /* 0xc */ s32 gim_no;
} PARA_DC_GIM;

typedef struct { // 0x8
    /* 0x0 */ DVECTOR str_offset;
    /* 0x4 */ s32 str_no;
} PARA_DC_EX0;

typedef struct { // 0x8
    /* 0x0 */ DVECTOR str_offset;
    /* 0x4 */ s32 str_no;
} PARA_DC_EX1;

typedef struct { // 0x18
    /* 0x00 */ DVECTOR str_offset;
    /* 0x04 */ s16 str_array[10];
} PARA_DC_EX2;

typedef struct { // 0x10
    /* 0x0 */ DVECTOR str_offset;
    /* 0x4 */ s32 str_no;
    /* 0x8 */ s32 pup_id[2];
} PARA_DC_EX3;

extern GIM_FORM GimForm_PLTA01;
extern GIM_FORM GimForm_PLTA02;
extern GIM_FORM GimForm_PLTA03;
extern GIM_FORM GimForm_PLTA04;
extern GIM_FORM GimForm_PLTA05;
extern GIM_FORM GimForm_PLTA06;
extern GIM_FORM GimForm_PLTA07;
extern GIM_FORM GimForm_PLTA08;
extern GIM_FORM GimForm_PLTA09;
extern GIM_FORM GimForm_PLTA10;
extern GIM_FORM GimForm_PLTA11;
extern GIM_FORM GimForm_PLTA12;
extern GIM_FORM GimForm_PLTB01;
extern GIM_FORM GimForm_PLTB02;
extern GIM_FORM GimForm_PLTB03;
extern GIM_FORM GimForm_PLTB04;
extern GIM_FORM GimForm_PLTB05;
extern GIM_FORM GimForm_PLTB06;
extern GIM_FORM GimForm_PLTB07;
extern GIM_FORM GimForm_PLTB08;
extern GIM_FORM GimForm_PLTB09;
extern GIM_FORM GimForm_PLTC01;
extern GIM_FORM GimForm_PLTC02;
extern GIM_FORM GimForm_PLTC03;
extern GIM_FORM GimForm_PLTC04;
extern GIM_FORM GimForm_PLTC05;
extern GIM_FORM GimForm_PLTC06;
extern GIM_FORM GimForm_PLTC07;
extern GIM_FORM GimForm_PLTC08;
extern GIM_FORM GimForm_PLTC09;
extern GIM_FORM GimForm_PLTD01;
extern GIM_FORM GimForm_PLTD02;
extern GIM_FORM GimForm_PLTD03;
extern GIM_FORM GimForm_PLTD04;
extern GIM_FORM GimForm_PLTD05;
extern GIM_FORM GimForm_PLTD06;
extern GIM_FORM GimForm_PLTD07;
extern GIM_FORM GimForm_PLTD08;
extern GIM_FORM GimForm_PLTD09;
extern GIM_FORM GimForm_PLTE01;
extern GIM_FORM GimForm_PLTE02;
extern GIM_FORM GimForm_PLTE03;
extern GIM_FORM GimForm_PLTE04;
extern GIM_FORM GimForm_PLTE05;
extern GIM_FORM GimForm_PLTE06;
extern GIM_FORM GimForm_PLTE07;
extern GIM_FORM GimForm_PLTE08;
extern GIM_FORM GimForm_PLTE09;
extern GIM_FORM GimForm_PLTF01;
extern GIM_FORM GimForm_PLTF02;
extern GIM_FORM GimForm_PLTF03;
extern GIM_FORM GimForm_PLTF04;
extern GIM_FORM GimForm_PLTF05;
extern GIM_FORM GimForm_PLTF06;
extern GIM_FORM GimForm_PLTF07;
extern GIM_FORM GimForm_PLTF08;
extern GIM_FORM GimForm_PLTF09;
extern GIM_FORM GimForm_SEL0000;
extern GIM_FORM GimForm_SEL0001;
extern GIM_FORM GimForm_SEL0002;
extern GIM_FORM GimForm_SEL0003;
extern GIM_FORM GimForm_SEL0005;
extern GIM_FORM GimForm_SEL0006;
extern GIM_FORM GimForm_SEL0007;
extern GIM_FORM GimForm_SEL0008;
extern GIM_FORM GimForm_SEL0010;
extern GIM_FORM GimForm_SEL0016;
extern GIM_FORM GimForm_SEL0019;
extern GIM_FORM GimForm_SEL0020;
extern GIM_FORM GimForm_SEL0100;
extern GIM_FORM GimForm_SEL0101;
extern GIM_FORM GimForm_SEL0102;
extern GIM_FORM GimForm_SEL0103;
extern GIM_FORM GimForm_SEL0104;
extern GIM_FORM GimForm_SEL0105;
extern GIM_FORM GimForm_SEL0106;
extern GIM_FORM GimForm_SEL0107;
extern GIM_FORM GimForm_SEL0111;
extern GIM_FORM GimForm_SEL0112;
extern GIM_FORM GimForm_SEL0113;
extern GIM_FORM GimForm_SEL0114;
extern GIM_FORM GimForm_SEL0115;
extern GIM_FORM GimForm_SEL0400;
extern GIM_FORM GimForm_SEL0401;
extern GIM_FORM GimForm_HANE01;
extern GIM_FORM GimForm_ZANKI;
extern GIM_FORM GimForm_LOGO;
extern GIM_FORM GimForm_PBYNAM;
extern GIM_FORM GimForm_CHR_SLASH;
extern GIM_FORM GimForm_MOM0007;
extern GIM_FORM GimForm_MOM0008;
extern GIM_FORM GimForm_MOM0009;
extern GIM_FORM GimForm_MOM0010;
extern GIM_FORM GimForm_KUMO1;
extern GIM_FORM GimForm_KUMO2;
extern GIM_FORM *GimForms[];
extern PARA_DC_STD ParaDcStd_Ttl_00;
extern PARA_DC_STD ParaDcStd_Ttl_01;
extern PARA_DC_STD ParaDcStd_Fil_04;
extern PARA_DC_STD ParaDcStd_Fil_05;
extern PARA_DC_STD ParaDcStd_Fil_06;
extern PARA_DC_STD ParaDcStd_Fil_07;
extern PARA_DC_STD ParaDcStd_Fil_08;
extern PARA_DC_STD ParaDcStd_Fil_09;
extern PARA_DC_STD ParaDcStd_Opt_00;
extern PARA_DC_STD ParaDcStd_Opt_01;
extern PARA_DC_STD ParaDcStd_Opt_02;
extern PARA_DC_STD ParaDcStd_Opt_03;
extern PARA_DC_STD ParaDcStd_Opt_04;
extern PARA_DC_STD ParaDcStd_Opt_05;
extern PARA_DC_STD ParaDcStd_Opt_06;
extern PARA_DC_STD ParaDcStd_Opt_07;
extern PARA_DC_STD ParaDcStd_Opt_08;
extern PARA_DC_STD ParaDcStd_Wmp_00;
extern PARA_DC_STD ParaDcStd_Wmp_01;
extern PARA_DC_STD ParaDcStd_Wmp_02;
extern PARA_DC_STD ParaDcStd_Gam_00;
extern PARA_DC_STD ParaDcStd_Gam_01;
extern PARA_DC_STD ParaDcStd_Gam_02;
extern PARA_DC_STD ParaDcStd_Gam_03;
extern PARA_DC_STD ParaDcStd_Gam_04;
extern PARA_DC_STD ParaDcStd_Gam_05;
extern PARA_DC_STD ParaDcStd_Mom_00;
extern PARA_DC_STD ParaDcStd_Mom_01;
extern PARA_DC_STD ParaDcStd_Mom_02;
extern PARA_DC_STD ParaDcStd_Mom_03;
extern PARA_DC_STD ParaDcStd_Pup_00;
extern PARA_DC_STD ParaDcStd_Pup_01;
extern PARA_DC_STD ParaDcStd_Pup_02;
extern PARA_DC_STD ParaDcStd_Pup_03;
extern PARA_DC_STD ParaDcStd_Pup_04;
extern PARA_DC_STD ParaDcStd_Pup_05;
extern PARA_DC_STD ParaDcStd_Pup_06;
extern PARA_DC_STD ParaDcStd_Pup_07;
extern PARA_DC_STD ParaDcStd_Pup_08;
extern PARA_DC_STD ParaDcStd_Pup_09;
extern PARA_DC_STD ParaDcStd_Pup_10;
extern PARA_DC_STD ParaDcStd_Pup_11;
extern PARA_DC_STD ParaDcStd_Pup_12;
extern PARA_DC_STD ParaDcStd_Pup_13;
extern PARA_DC_STD ParaDcStd_Pup_14;
extern PARA_DC_STD ParaDcStd_Pup_15;
extern PARA_DC_STD ParaDcStd_Pup_16;
extern PARA_DC_STD ParaDcStd_Pup_17;
extern PARA_DC_STD ParaDcStd_Pup_18;
extern PARA_DC_STD ParaDcStd_Pup_19;
extern PARA_DC_STD ParaDcStd_Pup_20;
extern PARA_DC_STD ParaDcStd_Pup_21;
extern PARA_DC_STD ParaDcStd_Pup_22;
extern PARA_DC_STD ParaDcStd_Pup_23;
extern PARA_DC_STD ParaDcStd_Pup_24;
extern PARA_DC_STD ParaDcStd_Tri_00;
extern PARA_DC_STD ParaDcStd_Tri_01;
extern PARA_DC_GIM ParaDcGim_Etc_00;
extern PARA_DC_GIM ParaDcGim_Etc_01;
extern PARA_DC_GIM ParaDcGim_Etc_02;
extern PARA_DC_GIM ParaDcGim_Etc_03;
extern PARA_DC_GIM ParaDcGim_Etc_04;
extern PARA_DC_GIM ParaDcGim_Etc_05;
extern PARA_DC_GIM ParaDcGim_Etc_06;
extern PARA_DC_GIM ParaDcGim_Etc_07;
extern PARA_DC_GIM ParaDcGim_Etc_08;
extern PARA_DC_GIM ParaDcGim_Etc_09;
extern PARA_DC_GIM ParaDcGim_Etc_10;
extern PARA_DC_EX0 ParaDcEx0_Stt_00;
extern PARA_DC_EX0 ParaDcEx0_Stt_01;
extern PARA_DC_EX0 ParaDcEx0_Stt_02;
extern PARA_DC_EX0 ParaDcEx0_Stt_03;
extern PARA_DC_EX0 ParaDcEx0_Stt_04;
extern PARA_DC_EX0 ParaDcEx0_Stt_05;
extern PARA_DC_EX0 ParaDcEx0_Stt_06;
extern PARA_DC_EX0 ParaDcEx0_Stt_07;
extern PARA_DC_EX0 ParaDcEx0_Stt_08;
extern PARA_DC_EX0 ParaDcEx0_Stt_09;
extern PARA_DC_EX0 ParaDcEx0_Stt_10;
extern PARA_DC_EX0 ParaDcEx0_Stt_11;
extern PARA_DC_EX0 ParaDcEx0_Stt_12;
extern PARA_DC_EX0 ParaDcEx0_Stt_13;
extern PARA_DC_EX0 ParaDcEx0_Stt_14;
extern PARA_DC_EX0 ParaDcEx0_Stt_15;
extern PARA_DC_EX0 ParaDcEx0_Stt_16;
extern PARA_DC_EX0 ParaDcEx0_Stt_17;
extern PARA_DC_EX0 ParaDcEx0_Stt_18;
extern PARA_DC_EX1 ParaDcEx1_Gjk_00;
extern PARA_DC_EX1 ParaDcEx1_Gjk_01;
extern PARA_DC_EX1 ParaDcEx1_Gjk_02;
extern PARA_DC_EX1 ParaDcEx1_Gjk_03;
extern PARA_DC_EX1 ParaDcEx1_Gjk_04;
extern PARA_DC_EX1 ParaDcEx1_Gjk_05;
extern PARA_DC_EX2 ParaDcEx2_Fil_00;
extern PARA_DC_EX2 ParaDcEx2_Fil_01;
extern PARA_DC_EX2 ParaDcEx2_Fil_02;
extern PARA_DC_EX2 ParaDcEx2_Fil_03;
extern PARA_DC_EX3 ParaDcEx3_Pup_25;
extern PARA_DC_EX3 ParaDcEx3_Pup_26;
extern PARA_DC_EX3 ParaDcEx3_Pup_27;
extern PARA_DC_EX3 ParaDcEx3_Pup_28;
extern PARA_DC_EX3 ParaDcEx3_Pup_29;
extern PARA_DC_EX3 ParaDcEx3_Pup_30;
extern PARA_DC_EX3 ParaDcEx3_Pup_31;
extern PARA_DC_EX3 ParaDcEx3_Pup_32;
extern PARA_DC_EX3 ParaDcEx3_Pup_33;
extern PARA_DC_EX3 ParaDcEx3_Pup_34;
extern PARA_DC_EX3 ParaDcEx3_Pup_35;
extern PARA_DC_EX3 ParaDcEx3_Pup_36;
extern PARA_DC_EX3 ParaDcEx3_Pup_37;
extern PARA_DC_EX3 ParaDcEx3_Pup_38;
extern PARA_DC_EX3 ParaDcEx3_Pup_39;
extern PARA_DC_EX3 ParaDcEx3_Pup_40;
extern PARA_DC_EX3 ParaDcEx3_Pup_41;
extern PARA_DC_EX3 ParaDcEx3_Pup_42;
extern PARA_DC_EX3 ParaDcEx3_Pup_43;
extern PARA_DC_EX3 ParaDcEx3_Pup_44;
extern PARA_DC_EX3 ParaDcEx3_Pup_45;
extern PARA_DC_EX3 ParaDcEx3_Pup_46;
extern PARA_DC_EX3 ParaDcEx3_Pup_47;
extern PARA_DC_EX3 ParaDcEx3_Pup_48;
extern PARA_DC_EX3 ParaDcEx3_Pup_49;
extern PARA_DC_EX3 ParaDcEx3_Pup_50;
extern PARA_DC_EX3 ParaDcEx3_Pup_51;
extern PARA_DC_EX3 ParaDcEx3_Pup_52;
extern PARA_DC_EX3 ParaDcEx3_Pup_53;
extern PARA_DC_EX3 ParaDcEx3_Pup_54;
extern PARA_DC_EX3 ParaDcEx3_Pup_55;
extern PARA_DC_EX3 ParaDcEx3_Pup_56;
extern PARA_DC_EX3 ParaDcEx3_Pup_57;
extern PARA_DC_EX3 ParaDcEx3_Pup_58;
extern PARA_DC_EX3 ParaDcEx3_Pup_59;
extern PARA_DC_EX3 ParaDcEx3_Pup_60;
extern PARA_DC_EX3 ParaDcEx3_Pup_61;
extern PARA_DC_EX3 ParaDcEx3_Pup_62;
extern PARA_DC_EX3 ParaDcEx3_Pup_63;
extern PARA_DC_EX3 ParaDcEx3_Pup_64;
extern PARA_DC_EX3 ParaDcEx3_Pup_65;
extern PARA_DC_EX3 ParaDcEx3_Pup_66;
extern PARA_DC_EX3 ParaDcEx3_Pup_67;
extern PARA_DC_EX3 ParaDcEx3_Pup_68;
extern PARA_DC_EX3 ParaDcEx3_Pup_69;
extern PARA_DC_EX3 ParaDcEx3_Pup_70;
extern PARA_DC_EX3 ParaDcEx3_Pup_71;
extern PARA_DC_EX3 ParaDcEx3_Pup_72;
extern PARA_DC_EX3 ParaDcEx3_Pup_73;
extern PARA_DC_EX3 ParaDcEx3_Pup_74;
extern PARA_DC_EX3 ParaDcEx3_Pup_75;
extern PARA_DC_EX3 ParaDcEx3_Pup_76;
extern PARA_DC_EX3 ParaDcEx3_Pup_77;
extern PARA_DC_EX3 ParaDcEx3_Pup_78;
extern PARA_DC_EX3 ParaDcEx3_Pup_79;
extern PARA_DC_EX3 ParaDcEx3_Pup_80;
extern PARA_DC_EX3 ParaDcEx3_Pup_81;
extern PARA_DC_EX3 ParaDcEx3_Pup_82;
extern PARA_DC_EX3 ParaDcEx3_Pup_83;
extern PARA_DC_EX3 ParaDcEx3_Pup_84;
extern PARA_DC_EX3 ParaDcEx3_Pup_85;
extern PARA_DC_EX3 ParaDcEx3_Pup_86;
extern PARA_DC_EX3 ParaDcEx3_Pup_87;
extern GIM_FORM *PlateForm_0[2];
extern GIM_FORM *PlateForm_1[2];
extern GIM_FORM *PlateForm_2[2];
extern GIM_FORM *PlateForm_3[2];
extern GIM_FORM *PlateForm_4[2];
extern GIM_FORM *PlateForm_5[2];
extern GIM_FORM *PlateForm_6[2];
extern GIM_FORM *PlateForm_7[2];
extern GIM_FORM **PlateForms[];
extern KZCOLOR FontColor_0[2];
extern KZCOLOR FontColor_1[2];
extern PLATE_INFO PlateInfo_Ttl_00;
extern PLATE_INFO PlateInfo_Ttl_01;
extern PLATE_INFO PlateInfo_Fil_00;
extern PLATE_INFO PlateInfo_Fil_01;
extern PLATE_INFO PlateInfo_Fil_02;
extern PLATE_INFO PlateInfo_Fil_03;
extern PLATE_INFO PlateInfo_Fil_04;
extern PLATE_INFO PlateInfo_Fil_05;
extern PLATE_INFO PlateInfo_Fil_06;
extern PLATE_INFO PlateInfo_Fil_07;
extern PLATE_INFO PlateInfo_Fil_08;
extern PLATE_INFO PlateInfo_Fil_09;
extern PLATE_INFO PlateInfo_Opt_00;
extern PLATE_INFO PlateInfo_Opt_01;
extern PLATE_INFO PlateInfo_Opt_02;
extern PLATE_INFO PlateInfo_Opt_03;
extern PLATE_INFO PlateInfo_Opt_04;
extern PLATE_INFO PlateInfo_Opt_05;
extern PLATE_INFO PlateInfo_Opt_06;
extern PLATE_INFO PlateInfo_Opt_07;
extern PLATE_INFO PlateInfo_Opt_08;
extern PLATE_INFO PlateInfo_Etc_00;
extern PLATE_INFO PlateInfo_Etc_01;
extern PLATE_INFO PlateInfo_Etc_02;
extern PLATE_INFO PlateInfo_Etc_03;
extern PLATE_INFO PlateInfo_Etc_04;
extern PLATE_INFO PlateInfo_Etc_05;
extern PLATE_INFO PlateInfo_Etc_06;
extern PLATE_INFO PlateInfo_Etc_07;
extern PLATE_INFO PlateInfo_Etc_08;
extern PLATE_INFO PlateInfo_Etc_09;
extern PLATE_INFO PlateInfo_Etc_10;
extern PLATE_INFO PlateInfo_Wmp_00;
extern PLATE_INFO PlateInfo_Wmp_01;
extern PLATE_INFO PlateInfo_Wmp_02;
extern PLATE_INFO PlateInfo_Wmp_03;
extern PLATE_INFO PlateInfo_Wmp_04;
extern PLATE_INFO PlateInfo_Wmp_05;
extern PLATE_INFO PlateInfo_Wmp_06;
extern PLATE_INFO PlateInfo_Wmp_07;
extern PLATE_INFO PlateInfo_Wmp_08;
extern PLATE_INFO PlateInfo_Wmp_09;
extern PLATE_INFO PlateInfo_Wmp_10;
extern PLATE_INFO PlateInfo_Wmp_11;
extern PLATE_INFO PlateInfo_Wmp_12;
extern PLATE_INFO PlateInfo_Wmp_13;
extern PLATE_INFO PlateInfo_Wmp_14;
extern PLATE_INFO PlateInfo_Wmp_15;
extern PLATE_INFO PlateInfo_Wmp_16;
extern PLATE_INFO PlateInfo_Wmp_17;
extern PLATE_INFO PlateInfo_Wmp_18;
extern PLATE_INFO PlateInfo_Wmp_20;
extern PLATE_INFO PlateInfo_Wmp_21;
extern PLATE_INFO PlateInfo_Wmp_22;
extern PLATE_INFO PlateInfo_Gam_00;
extern PLATE_INFO PlateInfo_Gam_01;
extern PLATE_INFO PlateInfo_Gam_02;
extern PLATE_INFO PlateInfo_Gam_03;
extern PLATE_INFO PlateInfo_Gam_04;
extern PLATE_INFO PlateInfo_Gam_05;
extern PLATE_INFO PlateInfo_Mom_00;
extern PLATE_INFO PlateInfo_Mom_01;
extern PLATE_INFO PlateInfo_Mom_02;
extern PLATE_INFO PlateInfo_Mom_03;
extern PLATE_INFO PlateInfo_Mom_04;
extern PLATE_INFO PlateInfo_Mom_05;
extern PLATE_INFO PlateInfo_Mom_06;
extern PLATE_INFO PlateInfo_Mom_07;
extern PLATE_INFO PlateInfo_Mom_08;
extern PLATE_INFO PlateInfo_Mom_09;
extern PLATE_INFO PlateInfo_Pup_00;
extern PLATE_INFO PlateInfo_Pup_01;
extern PLATE_INFO PlateInfo_Pup_02;
extern PLATE_INFO PlateInfo_Pup_03;
extern PLATE_INFO PlateInfo_Pup_04;
extern PLATE_INFO PlateInfo_Pup_05;
extern PLATE_INFO PlateInfo_Pup_06;
extern PLATE_INFO PlateInfo_Pup_07;
extern PLATE_INFO PlateInfo_Pup_08;
extern PLATE_INFO PlateInfo_Pup_09;
extern PLATE_INFO PlateInfo_Pup_10;
extern PLATE_INFO PlateInfo_Pup_11;
extern PLATE_INFO PlateInfo_Pup_12;
extern PLATE_INFO PlateInfo_Pup_13;
extern PLATE_INFO PlateInfo_Pup_14;
extern PLATE_INFO PlateInfo_Pup_15;
extern PLATE_INFO PlateInfo_Pup_16;
extern PLATE_INFO PlateInfo_Pup_17;
extern PLATE_INFO PlateInfo_Pup_18;
extern PLATE_INFO PlateInfo_Pup_19;
extern PLATE_INFO PlateInfo_Pup_20;
extern PLATE_INFO PlateInfo_Pup_21;
extern PLATE_INFO PlateInfo_Pup_22;
extern PLATE_INFO PlateInfo_Pup_23;
extern PLATE_INFO PlateInfo_Pup_24;
extern PLATE_INFO PlateInfo_Pup_25;
extern PLATE_INFO PlateInfo_Pup_26;
extern PLATE_INFO PlateInfo_Pup_27;
extern PLATE_INFO PlateInfo_Pup_28;
extern PLATE_INFO PlateInfo_Pup_29;
extern PLATE_INFO PlateInfo_Pup_30;
extern PLATE_INFO PlateInfo_Pup_31;
extern PLATE_INFO PlateInfo_Pup_32;
extern PLATE_INFO PlateInfo_Pup_33;
extern PLATE_INFO PlateInfo_Pup_34;
extern PLATE_INFO PlateInfo_Pup_35;
extern PLATE_INFO PlateInfo_Pup_36;
extern PLATE_INFO PlateInfo_Pup_37;
extern PLATE_INFO PlateInfo_Pup_38;
extern PLATE_INFO PlateInfo_Pup_39;
extern PLATE_INFO PlateInfo_Pup_40;
extern PLATE_INFO PlateInfo_Pup_41;
extern PLATE_INFO PlateInfo_Pup_42;
extern PLATE_INFO PlateInfo_Pup_43;
extern PLATE_INFO PlateInfo_Pup_44;
extern PLATE_INFO PlateInfo_Pup_45;
extern PLATE_INFO PlateInfo_Pup_46;
extern PLATE_INFO PlateInfo_Pup_47;
extern PLATE_INFO PlateInfo_Pup_48;
extern PLATE_INFO PlateInfo_Pup_49;
extern PLATE_INFO PlateInfo_Pup_50;
extern PLATE_INFO PlateInfo_Pup_51;
extern PLATE_INFO PlateInfo_Pup_52;
extern PLATE_INFO PlateInfo_Pup_53;
extern PLATE_INFO PlateInfo_Pup_54;
extern PLATE_INFO PlateInfo_Pup_55;
extern PLATE_INFO PlateInfo_Pup_56;
extern PLATE_INFO PlateInfo_Pup_57;
extern PLATE_INFO PlateInfo_Pup_58;
extern PLATE_INFO PlateInfo_Pup_59;
extern PLATE_INFO PlateInfo_Pup_60;
extern PLATE_INFO PlateInfo_Pup_61;
extern PLATE_INFO PlateInfo_Pup_62;
extern PLATE_INFO PlateInfo_Pup_63;
extern PLATE_INFO PlateInfo_Pup_64;
extern PLATE_INFO PlateInfo_Pup_65;
extern PLATE_INFO PlateInfo_Pup_66;
extern PLATE_INFO PlateInfo_Pup_67;
extern PLATE_INFO PlateInfo_Pup_68;
extern PLATE_INFO PlateInfo_Pup_69;
extern PLATE_INFO PlateInfo_Pup_70;
extern PLATE_INFO PlateInfo_Pup_71;
extern PLATE_INFO PlateInfo_Pup_72;
extern PLATE_INFO PlateInfo_Pup_73;
extern PLATE_INFO PlateInfo_Pup_74;
extern PLATE_INFO PlateInfo_Pup_75;
extern PLATE_INFO PlateInfo_Pup_76;
extern PLATE_INFO PlateInfo_Pup_77;
extern PLATE_INFO PlateInfo_Pup_78;
extern PLATE_INFO PlateInfo_Pup_79;
extern PLATE_INFO PlateInfo_Pup_80;
extern PLATE_INFO PlateInfo_Pup_81;
extern PLATE_INFO PlateInfo_Pup_82;
extern PLATE_INFO PlateInfo_Pup_83;
extern PLATE_INFO PlateInfo_Pup_84;
extern PLATE_INFO PlateInfo_Pup_85;
extern PLATE_INFO PlateInfo_Pup_86;
extern PLATE_INFO PlateInfo_Pup_87;
extern PLATE_INFO PlateInfo_Tri_00;
extern PLATE_INFO PlateInfo_Tri_01;
extern PLATE_INFO *Plates_Win_YesNo[];
extern PLATE_INFO *Plates_Ttl_Menu[];
extern PLATE_INFO *Plates_Fil_MakeSel[];
extern PLATE_INFO *Plates_Fil_FileSel[];
extern PLATE_INFO *Plates_Fil_DataSel[];
extern PLATE_INFO *Plates_Opt_Top[];
extern PLATE_INFO *Plates_Opt_Pad[];
extern PLATE_INFO *Plates_Opt_Sound[];
extern PLATE_INFO *Plates_Etc_PadExp0[];
extern PLATE_INFO *Plates_Etc_PadExp1[];
extern PLATE_INFO *Plates_Etc_PadExp2[];
extern PLATE_INFO *Plates_Etc_PadExp3[];
extern PLATE_INFO *Plates_Etc_PadExp4[];
extern PLATE_INFO *Plates_Etc_PadExp5[];
extern PLATE_INFO *Plates_Wmp_Status[];
extern PLATE_INFO *Plates_Wmp_Menu[];
extern PLATE_INFO *Plates_Gam_Pause[];
extern PLATE_INFO *Plates_Mom_Pause[];
extern PLATE_INFO *Plates_Gam_VOver[];
extern PLATE_INFO *Plates_Mom_Top[];
extern PLATE_INFO *Plates_Mom_Genju[];
extern PLATE_INFO *Plates_Pup_Top[];
extern PLATE_INFO *Plates_Pup_Group00[];
extern PLATE_INFO *Plates_Pup_Group01[];
extern PLATE_INFO *Plates_Pup_Group02[];
extern PLATE_INFO *Plates_Pup_Group03[];
extern PLATE_INFO *Plates_Pup_Group04[];
extern PLATE_INFO *Plates_Pup_Group05[];
extern PLATE_INFO *Plates_Pup_Group06[];
extern PLATE_INFO *Plates_Pup_Group07[];
extern PLATE_INFO *Plates_Pup_Group08[];
extern PLATE_INFO *Plates_Pup_Group09[];
extern PLATE_INFO *Plates_Pup_Group10[];
extern PLATE_INFO *Plates_Pup_Group11[];
extern PLATE_INFO *Plates_Pup_Group12[];
extern PLATE_INFO *Plates_Pup_Group13[];
extern PLATE_INFO *Plates_Pup_Group14[];
extern PLATE_INFO *Plates_Pup_Group15[];
extern PLATE_INFO *Plates_Pup_Group16[];
extern PLATE_INFO *Plates_Pup_Group17[];
extern PLATE_INFO *Plates_Pup_Group18[];
extern PLATE_INFO *Plates_Pup_Group19[];
extern PLATE_INFO *Plates_Pup_Group20[];
extern PLATE_INFO *Plates_Pup_Group21[];
extern PLATE_INFO *Plates_Pup_Group22[];
extern PLATE_INFO *Plates_Pup_Group23[];
extern PLATE_INFO *Plates_Pup_Group24[];
extern PLATE_INFO *Plates_Tri_TtlMenu[];
extern short int LineOffset_Win[];
extern short int LineOffset_Ttl[];
extern short int LineOffset_Fil[];
extern short int LineOffset_Opt[];
extern short int LineOffset_PadExp0[];
extern short int LineOffset_PadExp1[];
extern short int LineOffset_Status[];
extern short int LineOffset_WmpMenu[];
extern short int LineOffset_Pause[];
extern short int LineOffset_VOver[];
extern short int LineOffset_MomTop[];
extern short int LineOffset_Genju[];
extern short int LineOffset_Theater[];
extern short int LineOffset_TriTtl[];
extern short int RowOffset_Win[];
extern short int RowOffset_Ttl[];
extern short int RowOffset_Fil[];
extern short int RowOffset_Opt[];
extern short int RowOffset_PadExp0[];
extern short int RowOffset_PadExp1[];
extern short int RowOffset_PadExp2[];
extern short int RowOffset_PadExp3[];
extern short int RowOffset_Status[];
extern short int RowOffset_WmpMenu[];
extern short int RowOffset_Pause[];
extern short int RowOffset_VOver[];
extern short int RowOffset_MomTop[];
extern short int RowOffset_Genju[];
extern short int RowOffset_Theater[];
extern short int RowOffset_TriTtl[];
extern short int Delay_Win[];
extern short int Delay_Ttl[];
extern short int Delay_Fil[];
extern short int Delay_Opt[];
extern short int Delay_PadExp[];
extern short int Delay_Status[];
extern short int Delay_WmpMenu[];
extern short int Delay_Pause[];
extern short int Delay_VOver[];
extern short int Delay_MomTop[];
extern short int Delay_Genju[];
extern short int Delay_Theater[];
extern short int Delay_TriTtl[];
extern SELECT_INFO SelectInfo_Win_YesNo;
extern SELECT_INFO SelectInfo_Ttl_Menu;
extern SELECT_INFO SelectInfo_Fil_MakeSel;
extern SELECT_INFO SelectInfo_Fil_Confirm;
extern SELECT_INFO SelectInfo_Fil_FileSel;
extern SELECT_INFO SelectInfo_Fil_DataSel;
extern SELECT_INFO SelectInfo_Opt_Top;
extern SELECT_INFO SelectInfo_Opt_Pad;
extern SELECT_INFO SelectInfo_Opt_Sound0;
extern SELECT_INFO SelectInfo_Opt_Sound1;
extern SELECT_INFO SelectInfo_Etc_PadExp0;
extern SELECT_INFO SelectInfo_Etc_PadExp1;
extern SELECT_INFO SelectInfo_Etc_PadExp2;
extern SELECT_INFO SelectInfo_Etc_PadExp3;
extern SELECT_INFO SelectInfo_Etc_PadExp4;
extern SELECT_INFO SelectInfo_Etc_PadExp5;
extern SELECT_INFO SelectInfo_Etc_PadExp6;
extern SELECT_INFO SelectInfo_Wmp_Status;
extern SELECT_INFO SelectInfo_Wmp_Menu;
extern SELECT_INFO SelectInfo_Gam_Pause;
extern SELECT_INFO SelectInfo_Mom_Pause;
extern SELECT_INFO SelectInfo_Gam_VOver;
extern SELECT_INFO SelectInfo_Mom_Top;
extern SELECT_INFO SelectInfo_Mom_Genju;
extern SELECT_INFO SelectInfo_Pup_Top;
extern SELECT_INFO SelectInfo_Pup_Group00;
extern SELECT_INFO SelectInfo_Pup_Group01;
extern SELECT_INFO SelectInfo_Pup_Group02;
extern SELECT_INFO SelectInfo_Pup_Group03;
extern SELECT_INFO SelectInfo_Pup_Group04;
extern SELECT_INFO SelectInfo_Pup_Group05;
extern SELECT_INFO SelectInfo_Pup_Group06;
extern SELECT_INFO SelectInfo_Pup_Group07;
extern SELECT_INFO SelectInfo_Pup_Group08;
extern SELECT_INFO SelectInfo_Pup_Group09;
extern SELECT_INFO SelectInfo_Pup_Group10;
extern SELECT_INFO SelectInfo_Pup_Group11;
extern SELECT_INFO SelectInfo_Pup_Group12;
extern SELECT_INFO SelectInfo_Pup_Group13;
extern SELECT_INFO SelectInfo_Pup_Group14;
extern SELECT_INFO SelectInfo_Pup_Group15;
extern SELECT_INFO SelectInfo_Pup_Group16;
extern SELECT_INFO SelectInfo_Pup_Group17;
extern SELECT_INFO SelectInfo_Pup_Group18;
extern SELECT_INFO SelectInfo_Pup_Group19;
extern SELECT_INFO SelectInfo_Pup_Group20;
extern SELECT_INFO SelectInfo_Pup_Group21;
extern SELECT_INFO SelectInfo_Pup_Group22;
extern SELECT_INFO SelectInfo_Pup_Group23;
extern SELECT_INFO SelectInfo_Pup_Group24;
extern SELECT_INFO SelectInfo_Tri_TtlMenu;
extern SELECT_INFO *Selectors[];
extern GIM_FORM *WindowParts_00[9];
extern GIM_FORM *WindowParts_01[9];
extern GIM_FORM *WindowParts_02[9];
extern GIM_FORM *WindowParts_03[9];
extern GIM_FORM *WindowParts_04[9];
extern GROUND_INFO GroundInfo_Win_Std;
extern GROUND_INFO GroundInfo_Opt_ScrExplain;
extern GROUND_INFO GroundInfo_Opt_HelpInfo;
extern GROUND_INFO GroundInfo_Opt_Adjust;
extern GROUND_INFO GroundInfo_Nam_Entry;
extern GROUND_INFO GroundInfo_Mom_PlyDisp;
extern GROUND_INFO GroundInfo_Mom_PlyCtrl;
extern GROUND_INFO GroundInfo_Wmp_Place;
extern GROUND_INFO GroundInfo_Mom_Message;
extern GROUND_INFO *Grounds[];
extern WINDOW_INFO WindowInfo_Mem_00;
extern WINDOW_INFO WindowInfo_Mem_01;
extern WINDOW_INFO WindowInfo_Mem_02;
extern WINDOW_INFO WindowInfo_Mem_03;
extern WINDOW_INFO WindowInfo_Mem_04;
extern WINDOW_INFO WindowInfo_Mem_05;
extern WINDOW_INFO WindowInfo_Mem_06;
extern WINDOW_INFO WindowInfo_Mem_07;
extern WINDOW_INFO WindowInfo_Mem_08;
extern WINDOW_INFO WindowInfo_Mem_09;
extern WINDOW_INFO WindowInfo_Mem_10;
extern WINDOW_INFO WindowInfo_Mem_11;
extern WINDOW_INFO WindowInfo_Mem_12;
extern WINDOW_INFO WindowInfo_Mem_13;
extern WINDOW_INFO WindowInfo_Mem_14;
extern WINDOW_INFO WindowInfo_Mem_15;
extern WINDOW_INFO WindowInfo_Mem_16;
extern WINDOW_INFO WindowInfo_Mem_17;
extern WINDOW_INFO WindowInfo_Mem_18;
extern WINDOW_INFO WindowInfo_Mem_19;
extern WINDOW_INFO WindowInfo_Etc_00;
extern WINDOW_INFO WindowInfo_Etc_01;
extern WINDOW_INFO WindowInfo_Etc_02;
extern WINDOW_INFO WindowInfo_Etc_03;
extern WINDOW_INFO WindowInfo_Etc_04;
extern WINDOW_INFO WindowInfo_Etc_05;
extern WINDOW_INFO *Windows[];
extern KZCOLOR A_ON;
extern KZCOLOR A_OFF;
extern KZCOLOR GCOL_STD;
extern KZCOLOR GCOL_PSH;
extern KZCOLOR GCOL_MRK;
extern KZCOLOR GCOL_SND;
extern KZCOLOR FCOL_STD;
extern DVECTOR ORIGIN;
extern DVECTOR FULLSCR;
extern DVECTOR GIMBASE_SNDMES;
extern DVECTOR GIMOFFSET_YUME;
extern DVECTOR GIMOFFSET_FLCK;
extern DVECTOR GIMOFFSET_DOLL;
extern DVECTOR GIMOFFSET_SLASH;
extern DVECTOR NUMOFFSET_YUME;
extern DVECTOR NUMOFFSET_DOLL0;
extern DVECTOR NUMOFFSET_DOLL1;
extern DVECTOR NUMOFFSET_GENJU;

extern void kzTD_Set_GsEnv_Std();
extern GIM_FORM* kzGIM_Get_Form(s32 gim_no);
extern void kzGIM_Draw(DVECTOR *sxy, u32 sz, KZCOLOR *col, s32 gim_no);
extern void kzGIM_Draw_Eff(DVECTOR *sxy, u32 sz, KZCOLOR *col, s32 gim_no);
extern void kzTD_Init_Fade(s32 mode);
extern s32 kzTD_Set_Fade(s32 mode);
extern void kzTD_Draw_Fade();
extern void kzTD_Clear_LastInfo();
extern s8 kzTD_Get_IdxPlate(s32 sel_no);
extern u8 kzTD_Get_SelFlag(s32 sel_no);
extern s32 kzTD_Get_PuppetID(s32 sel_no, s32 idx);
extern void kzTD_Set_PlateDisp(s32 sel_no, s32 idx, u8 flag);
extern void kzTD_Set_PlateStr(s32 sel_no, s32 idx, s16 *str);
extern void kzTD_Draw_Plate_Std(void *arg, s32 idx);
extern void kzTD_Draw_Contents_Std(void *arg, s32 idx);
extern void kzTD_Draw_Contents_Gim(void *arg, s32 idx);
extern void kzTD_Draw_Contents_Stt(void *arg, s32 idx);
extern void kzTD_Draw_Contents_Gjk(void *arg, s32 idx);
extern void kzTD_Draw_Contents_Fil(void *arg, s32 idx);
extern void kzTD_Draw_Contents_Tht(void *arg, s32 idx);
extern void kzTD_Draw_Mark_Std(void *arg);
extern void kzTD_CsrMove_Up(s32 sel_no);
extern void kzTD_CsrMove_Down(s32 sel_no);
extern void kzTD_CsrMove_Left(s32 sel_no);
extern void kzTD_CsrMove_Right(s32 sel_no);
extern void kzTD_PageMove_Left(s32 sel_no);
extern void kzTD_PageMove_Right(s32 sel_no);
extern void kzTD_Init_Selector(s32 sel_no, s32 idx_page, s32 idx_plate);
extern s32 kzTD_Draw_Selector(s32 sel_no);
extern void kzTD_Close_Selector(s32 sel_no, s32 mode);
extern void kzTD_Erase_Selector(s32 sel_no);
extern void kzTD_Init_SelViewer(s32 sel_no, s32 idx_page, s32 idx_plate);
extern void kzTD_Draw_SelViewer(s32 sel_no);
extern void kzTD_Draw_Ground(s32 grnd_no);
extern void kzTD_Draw_SendMes();
extern void kzTD_Init_Window(s32 win_no, s32 idx_page, s32 idx_plate);
extern s32 kzTD_Draw_Window(s32 win_no);

#endif